network_compression_threshold: 256
remote_ping_timeout: 5000
remote_ping_cache: -1
online_mode: true
forge_support: false
max_packets_per_second: 4096
servers:
  BeastSMP:
    motd: '§b§l❖ §c§lBeastSMP §6§l1.21 §b§l❖\n§b❖ §7§lDiscord\: §bdiscord.gg/yCNSKMyS ❖'
    address: localhost:25566
    restricted: false
  SMP:
    motd: '\u00a75                   \u06de\u00a74\u00a7l  SMP Server \u00a75\u06de\n        \u00a76\u00a7l\u21e8\u00a7d\u00a7k   BeastSMP\u00a7c  By BeastSMP \u00a7d\u00a7kPMStsaeB.   \u00a76\u21e6'
    address: 109.69.175.92:25565
    restricted: false
disabled_commands:
- disabledcommandhere
max_packets_data_per_second: 33554432
reject_transfers: false
player_limit: 1000
prevent_proxy_connections: false
connection_throttle_limit: 3
connection_throttle: 4000
log_commands: false
log_pings: true
stats: 530d2372-eb14-49f8-b313-8e129a503dfd
groups:
  md_5:
  - admin
ip_forward: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.alertraw
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
  - bungeecord.command.perms
listeners:
- query_port: 25565
  motd: |-
    &b&l❖ &c&lBeastSMP &6&l1.21 &b&l❖
    &b❖ &7&lDiscord: &bdiscord.gg/yCNSKMyS &b❖
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - BeastSMP
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1000
  tab_size: 60
  force_default_server: false
enforce_secure_profile: false
server_connect_timeout: 5000
timeout: 30000
